define(['handlebars'], function(Handlebars) {

return Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  var buffer = "";


  buffer += "<div class=\"row fnIntroTransition\">\n	<div class=\"col-sm-12\">\n		<div id=\"r-score\" style=\"margin: 5px\">\n		</div>\n	</div>\n</div>\n\n"
    + "\n\n<div class=\"row fnIntroTransition\">\n	<div class=\"col-sm-6\">\n		<div class=\"box\">\n			<h3><strong>Hvem</strong> har bolden: </h3>\n\n			<div style=\"position:relative\">\n				<img src=\"img/horizontal-pitch-narrow.svg\" style=\"width: 100%\"/>\n\n				<ul class=\"link-list\" style=\"position: absolute; left: 0; top: 0;\">\n					<li><a class=\"btn-event\"><span>Os</span></a></li>\n					<li><a class=\"btn-event\"><span>Neutral</span></a></li>\n					<li><a class=\"btn-event\"><span>Dem</span></a></li>\n				</ul>\n			</div>\n		</div>\n	</div>\n	<div class=\"col-sm-6\">\n		<div class=\"box\">\n			<h3><strong>hvor</strong> er bolden: </h3>\n			<img src=\"img/horizontal-pitch-narrow.svg\" style=\"width: 100%\"/>\n		</div>\n	</div>	\n</div>\n\n<div class=\"row fnIntroTransition\">\n	<div class=\"col-sm-12\">\n		<div class=\"box\">\n			<h3>Match <strong>events</strong>: </h3>\n\n			<ul class=\"link-list\">\n				<li>\n					<a class=\"btn-event\">\n						<div style=\"text-align: center\">Boldtab</div>\n						<div style=\"text-align: center\">Makienok</div>\n						<div style=\"text-align: center\">\n							<img src=\"img/horizontal-pitch-narrow.svg\" style=\"width: 95%\"/>\n						</div>\n\n					</a>\n				</li><li>\n					<a class=\"btn-event\">\n						<div style=\"text-align: center\">Boldtab</div>\n						<div style=\"text-align: center\">Makienok</div>\n						<div style=\"text-align: center\">\n							<img src=\"img/horizontal-pitch-narrow.svg\" style=\"width: 95%\"/>\n						</div>\n\n					</a>\n				</li><li>\n					<a class=\"btn-event\">\n						<div style=\"text-align: center\">Boldtab</div>\n						<div style=\"text-align: center\">Makienok</div>\n						<div style=\"text-align: center\">\n							<img src=\"img/horizontal-pitch-narrow.svg\" style=\"width: 95%\"/>\n						</div>\n\n					</a>\n				</li><li>\n					<a class=\"btn-event\">\n						<div style=\"text-align: center\">Boldtab</div>\n						<div style=\"text-align: center\">Makienok</div>\n						<div style=\"text-align: center\">\n							<img src=\"img/horizontal-pitch-narrow.svg\" style=\"width: 95%\"/>\n						</div>\n\n					</a>\n				</li>\n			</ul>\n		</div>\n	</div>\n</div>";
  return buffer;
  })

});