define(['handlebars'], function(Handlebars) {

return Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  var buffer = "";


  buffer += "\n<div class=\"matchreport type1\">\n    <div class=\"topmenu\">\n\n    </div>\n    <div class=\"topbar\">\n        <div class=\"clock first\">\n            <span style=\"width: 25%\"></span>\n        </div>\n        <div class=\"score\">2 - 2</div>\n        <div class=\"clock second\"></div>\n    </div>\n    <div class=\"middle\">\n\n        <div class=\"row\">\n            <div class=\"col-sm-5\">\n                <div class=\"buttons\">\n                    <button class=\"btn-scout\">Mål</button>\n                    <button class=\"btn-scout\">Skud</button>\n                    <button class=\"btn-scout\">Gult Kort</button>\n                    <button class=\"btn-scout\">Rødt Kort</button>\n                    <button class=\"btn-scout\">Hjørnespark</button>\n                    <button class=\"btn-scout\">Indkast</button>\n                    <button class=\"btn-scout\">Offside</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                </div>\n            </div>\n            <div class=\"col-sm-2\">\n                <div class=\"sign\">\n                    1<br/>\n                    Skud\n                </div>\n                <div class=\"sign\">TEST</div>\n                <div class=\"sign\">TEST</div>\n                <div class=\"sign\">TEST</div>\n                <div class=\"sign\">TEST</div>\n                <div class=\"sign\">TEST</div>\n            </div>\n            <div class=\"col-sm-5\">\n                <div class=\"buttons\">\n                    <button class=\"btn-scout\">Mål</button>\n                    <button class=\"btn-scout\">Skud</button>\n                    <button class=\"btn-scout\">Gult Kort</button>\n                    <button class=\"btn-scout\">Rødt Kort</button>\n                    <button class=\"btn-scout\">Hjørnespark</button>\n                    <button class=\"btn-scout\">Indkast</button>\n                    <button class=\"btn-scout\">Offside</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                    <button class=\"btn-scout\">Frispark</button>\n                </div>\n            </div>\n        </div>\n    </div>\n    <div class=\"bottom\">\n\n    </div>\n</div>\n\n"
    + "\n";
  return buffer;
  })

});