define(['handlebars'], function(Handlebars) {

return Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  


  return "<div class=\"row\">\n    <div id=\"matchreport-top\" class=\"col-sm-12 time-container\">\n        \n    </div>\n</div>\n\n<div class=\"row\">\n    <div id=\"matchreport-left\" class=\"col-sm-1\" style=\"padding-right: 0\">\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-random\" style=\"font-size: 3em\"></span></div>\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-retweet\" style=\"font-size: 3em\"></span></div>\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-th-large\" style=\"font-size: 3em\"></span></div>\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-tower\" style=\"font-size: 3em\"></span></div>\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-usd\" style=\"font-size: 3em\"></span></div>\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-user\" style=\"font-size: 3em\"></span></div>\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-stats\" style=\"font-size: 3em\"></span></div>\n        <div style=\"text-align: center; margin: 10px 0\"><span class=\"glyphicon glyphicon-road\" style=\"font-size: 3em\"></span></div>\n    </div>\n    <div id=\"matchreport-middle\" class=\"col-sm-9\" style=\"padding: 0\">\n        \n    </div>\n    <div id=\"matchreport-right\" class=\"col-sm-2\" style=\"padding-left: 0\">\n        <ul class=\"list-group\">\n          <li class=\"list-group-item\"><span class=\"badge badge-success\">22&prime;</span> Aflevering</li>\n          <li class=\"list-group-item\"><span class=\"badge badge-success\">23&prime;</span> Aflevering</li>\n          <li class=\"list-group-item\"><span class=\"badge badge-danger\">25&prime;</span> Skud</li>\n          <li class=\"list-group-item\"><span class=\"badge badge-success\">28&prime;</span> Aflevering</li>\n          <li class=\"list-group-item\"><span class=\"badge badge-success\">29&prime;</span> Aflevering</li>\n          <li class=\"list-group-item\"><span class=\"badge badge-danger\">33&prime;</span> Aflevering</li>\n          <li class=\"list-group-item\"><span class=\"badge badge-success\">35&prime;</span> Skud</li>\n          <li class=\"list-group-item\"><span class=\"badge badge-danger\">37&prime;</span> Aflevering</li>\n        </ul>\n    </div>\n</div>\n\n<div class=\"row\">\n    <div id=\"matchreport-bottom\" class=\"col-sm-12\">\n        BOTTOM\n    </div>\n</div>";
  })

});