define(['handlebars'], function(Handlebars) {

return Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  


  return "<div class=\"navbar navbar-inverse\">\n        <div class=\"container\">\n            <div class=\"navbar-header\">\n                <button class=\"navbar-toggle\" data-target=\".navbar-collapse\"\n                data-toggle=\"collapse\" type=\"button\"><span class=\"icon-bar\"></span>\n                <span class=\"icon-bar\"></span> <span class=\n                \"icon-bar\"></span></button> <a class=\"navbar-brand\" href=\n                \"#\">BetterTeam</a>\n            </div>\n\n            <div class=\"navbar-collapse collapse\">\n                <ul class=\"nav navbar-nav\">\n                    <li>\n                        <a href=\"#/players/\">Players</a>\n                    </li>\n\n                    <li>\n                        <a href=\"#/matches/\">Matches</a>\n                    </li>\n\n                    <li class=\"visible-xs\">\n                        <a href=\"#login\">Login</a>\n                    </li>\n                </ul>\n\n                <ul class=\"nav navbar-nav navbar-right visible-sm\">\n                    <li class=\"dropdown\">\n                        <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\n                        \"#\">Login <b class=\"caret\"></b></a>\n\n                        <ul class=\"dropdown-menu\">\n                            <li>\n                                <form>\n                                    <div class=\"form-group\">\n                                        <input class=\"form-control\" placeholder=\n                                        \"Email\" type=\"text\">\n                                    </div>\n\n                                    <div class=\"form-group\">\n                                        <input class=\"form-control\" placeholder=\n                                        \"Password\" type=\"password\">\n                                    </div><button class=\"btn btn-success\" type=\n                                    \"submit\">Sign in</button>\n                                </form>\n                            </li>\n                        </ul>\n                    </li>\n                </ul>\n\n                <form class=\"navbar-form navbar-right visible-md visible-lg\">\n                    <div class=\"form-group\">\n                        <input class=\"form-control\" placeholder=\"Email\" type=\n                        \"text\">\n                    </div>\n\n                    <div class=\"form-group\">\n                        <input class=\"form-control\" placeholder=\"Password\" type=\n                        \"password\">\n                    </div><button class=\"btn btn-success\" type=\"submit\">Sign\n                    in</button>\n                </form>\n            </div><!--/.navbar-collapse -->\n        </div>\n    </div>\n";
  })

});